spring.application.name=servicio-comunicaciones
server.port=8083

spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/db_comunicaciones}

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin}