sonar.projectKey=colegio-servicio-academico
sonar.projectName=Servicio Academico - Colegio O'Higgins
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.host.url=http://localhost:9000
sonar.token=TU_TOKEN_AQUI